### ISSUE TITLE
4 pom.xml present in the repo, only 2 stack reports generated

### ISSUE THREAD

**Issue by dev-gaur** [fabric8-analytics/fabric8-analytics-vscode-extension#72] opened 2018-01-18 09:52 UTC
Repository : https://github.com/invincibleJai/maven-multi-module-example-2

**Comment by invincibleJai** [comment] 2018-01-22 15:27
Thanks @dev-gaur , possibly duplicate of https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/63

**Closed** 2018-01-23 02:39 UTC
Labels: duplicate
