### ISSUE TITLE
[BUG] VSCode comment not working

### ISSUE THREAD

**Issue by hemangajmera** [fabric8-analytics/fabric8-analytics-vscode-extension#313] opened 2019-06-26 05:32 UTC
Once this extension is added, and if I do `Ctrl + /` for commenting any line in any xml file, it uses java language comment instead of xml comment. This extension should not affect comment.

In short expected `<!--` and  `-->` for any xml file, but getting `//` in the beginning of line when invoke `Ctrl /` shortcut

**Comment by arajkumar** [comment] 2019-08-22 06:46
@hemangajmera , I couldn't reproduce the issue with the vscode 1.36.1., hence closing this. Feel free to reopen the issue along with steps to reproduce. Thanks.

**Comment by arajkumar** [comment] 2019-08-22 06:46
@hemangajmera , I couldn't reproduce the issue with the vscode 1.36.1., hence closing this. Feel free to reopen the issue along with steps to reproduce. Thanks.

**Comment by arajkumar** [comment] 2019-08-22 09:34
I will wait for feedback from other developers. cc: @miteshvp @invincibleJai @SriKrishnaPaparaju @SamuelStuchly

**Comment by arajkumar** [comment] 2019-08-27 06:53
Couldn't reproduce it.

**Closed by arajkumar** 2019-08-27 06:53 UTC
Labels: fix-for-0.13
