### ISSUE TITLE
[BUG] Same dependencies showing up as analyzed and unknown dependencies

### ISSUE THREAD

**Issue by SriKrishnaPaparaju** [fabric8-analytics/fabric8-analytics-vscode-extension#320] opened 2019-08-06 15:09 UTC
**Describe the bug**
Same dependencies showing up as analyzed and unknown dependencies
**To Reproduce**
Try stack report for this manifest file: pom.xml
[https://gist.github.com/SriKrishnaPaparaju/eaf77f5d24106a229e6495203c4af86a
](https://gist.github.com/SriKrishnaPaparaju/eaf77f5d24106a229e6495203c4af86a)
**Expected behavior**

**Screenshots**
A dependency either should be an analyzed / unknown dependency
**Logs**
If applicable, attach logs.
<img width="1425" alt="Screen Shot 2019-08-06 at 8 38 25 PM" src="https://user-images.githubusercontent.com/42730908/62551803-3d013e00-b88a-11e9-960c-b3573464ca93.png">
<img width="1465" alt="Screen Shot 2019-08-06 at 8 39 14 PM" src="https://user-images.githubusercontent.com/42730908/62551829-47bbd300-b88a-11e9-9637-69765fcb4ee5.png">

**VSCode(please complete the following information):**
 - OS: [e.g. macOS]
 - VSCode version [e.g. 1.33.1]
 - Dependency Analytics Version [e.g. 0.0.22]

**CHE7/Theia(please complete the following information):**
 - OS: [e.g. macOS]
 - Browser [e.g. chrome]
 - CHE/Theia version 
 - Dependency Analytics Version [e.g. 0.0.22]

**Additional context**

**Comment by arajkumar** [comment] 2019-08-08 06:57
I couldn't reproduce the issue on my dev environment.

**Comment by miteshvp** [comment] 2019-08-21 09:24
This issue is not producible. I used the latest dev vsix as well as marketplace.

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/17736013/63419465-7d33f500-c422-11e9-9415-64941b5018bd.png">

**Comment by miteshvp** [comment] 2019-08-21 09:29
@SriKrishnaPaparaju - this is not reproducible. You can give a fresh try again.

**Comment by miteshvp** [comment] 2019-08-26 04:07
@arajkumar - this should be tested as part of vscode testing exercise.

**Comment by miteshvp** [comment] 2019-08-26 09:47
Closing this as this is not reproducible during the vscode testing exercise.

**Closed by miteshvp** 2019-08-26 09:47 UTC
Labels: fix-for-0.13
