### ISSUE TITLE
After updated of v0.7, some mvn error always appear.

### ISSUE THREAD

**Issue by Twistz1z** [fabric8-analytics/fabric8-analytics-vscode-extension#660] opened 2023-11-15 10:26 UTC
![image](https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/assets/73639790/ab38a5cd-a371-4c6d-96dd-b7590ee565a3)
![image](https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/assets/73639790/8a301ae0-6c31-4c22-bb04-72f8bce76f0e)

The issues look like mvn's problem, did anyone know what problem is it?
Should I upgrade or demote MVN or change the configuration of it?

**Comment by Ivo-Andrade-Taxation-Mind** [comment] 2023-11-21 14:14
Does the censored path contain a space character?, figured to ask since I've filed a similar issue (#657), and it also fails trying to run a `mvn -q clean -f <path>` command.

**Comment by stev-tig** [comment] 2023-11-24 05:29
Hi, I've encountered this as well

In my case it copied my parent pom.xml to /tmp/something/ directory to run mvn help:effective-pom there and it failed to find the child project's pom.xml in /tmp/something/ directory

**Comment by IlonaShishov** [comment] 2023-12-25 10:34
Hi @Twistz1z ,
Thank you for reaching out,
It seems like the issue you are describing is the same as in #657 ,
We will investigate this and provide a solution in future versions.

**Comment by zvigrinberg** [comment] 2024-01-18 12:43
If the issue is caused by a space in the path, then the following [PR](https://github.com/RHEcosystemAppEng/exhort-javascript-api/pull/100) solve this, and it will be included in the next release of the extension.

**Closed** 2024-02-05 09:16 UTC
