### ISSUE TITLE
Discrepancy related unknown dependencies

### ISSUE THREAD

**Issue by SriKrishnaPaparaju** [fabric8-analytics/fabric8-analytics-vscode-extension#253] opened 2019-01-07 03:08 UTC
All the dependencies show up as 'unknown' and still see recommendations for companion packages.
<img width="983" alt="screen shot 2019-01-07 at 8 36 03 am" src="https://user-images.githubusercontent.com/42730908/50746976-969f7c80-1257-11e9-972e-f6cc5d4194b9.png">

**Comment by samuzzal-choudhury** [comment] 2019-01-07 04:40
@SriKrishnaPaparaju could you please share the link to the repo?

**Comment by rootAvish** [comment] 2019-01-07 07:53
The recommenders do not care whether the graph knows the packages or not, the only possible alternative here is to filter the companions as well if the packages are unknown to the graph. Such filtering if required, cannot be done on the recommender service's side itself and would need a change in backbone.

**Comment by invincibleJai** [comment] 2019-02-19 09:26
is someone working on this?

**Comment by invincibleJai** [comment] 2019-03-27 06:47
@samuzzal-choudhury is someone looking into this?

**Comment by miteshvp** [comment] 2019-08-21 07:53
@SriKrishnaPaparaju - please provide the manifest file and also the stack-id if you have for this stack request. TBH @SamuelStuchly , this looks to be handled at backbone layer.

**Comment by miteshvp** [comment] 2019-08-26 04:06
Unassigning myself. This should be handled at Backbone. @samuzzal-choudhury - please assign this to yourself

**Comment by yzainee** [comment] 2019-08-26 07:07
@samuzzal-choudhury I think its not a bug. We show recommendations based on the user's stack. For unknown deps, its a case of deps not present in the graph, which eventually will get populated via the unknown flow.

**Comment by samuzzal-choudhury** [comment] 2019-08-26 07:19
@yzainee In my opinion, this still requires handling at the API side as this makes the user experience inconsistent. Possibly (I am yet to check this), we can add a filter at the API layer for recommendations when analyzed dependencies count is zero.

**Closed** 2019-08-29 09:30 UTC
Labels: bug, fix-for-0.13

**Comment by samuzzal-choudhury** [comment] 2019-08-29 13:26
The changes have been moved to production. Hence, closing the issue.
