### ISSUE TITLE
[BUG] Stack report never shows up

### ISSUE THREAD

**Issue by SriKrishnaPaparaju** [fabric8-analytics/fabric8-analytics-vscode-extension#364] opened 2019-12-21 11:56 UTC
**Describe the bug**
Stack never shows up for this repo: https://github.com/eclipse/che/. The status message 'Analyzing application dependencies..' never goes away.

**Expected behavior**
Stack report shows up.

**Screenshots**

**Logs**
If applicable, attach logs.

**VSCode(please complete the following information):**
 - OS: [e.g. macOS] macOS
 - VSCode version [e.g. 1.33.1] 1.41.0
 - Dependency Analytics Version [e.g. 0.0.22] 0.0.13

**Comment by arajkumar** [comment] 2019-12-24 09:47
Actually it is a regression of https://github.com/fabric8-analytics/fabric8-analytics-server/pull/592.
From vscode extension we look for 'error' property incase of HTTP status code 202. Above mentioned PR renamed the property to 'message' which is a root cause of this issue.

It will be fixed by https://github.com/fabric8-analytics/fabric8-analytics-server/pull/595.

**Closed by arajkumar** 2019-12-24 09:47 UTC
Labels: Analyzing
