### ISSUE TITLE
[BUG] Few times, stack report shows zero dependencies

### ISSUE THREAD

**Issue by SriKrishnaPaparaju** [fabric8-analytics/fabric8-analytics-vscode-extension#321] opened 2019-08-06 15:20 UTC
**Describe the bug**

**To Reproduce**
try stack report for this manifest file : https://gist.github.com/SriKrishnaPaparaju/daa0dec127c8af264ecf08effc33d251

**Expected behavior**

**Screenshots**
<img width="1476" alt="Screen Shot 2019-08-06 at 8 17 06 PM" src="https://user-images.githubusercontent.com/42730908/62552772-d4b35c00-b88b-11e9-8a6d-8113a82ffd80.png">

**Logs**
If applicable, attach logs.

**VSCode(please complete the following information):**
 - OS: [e.g. macOS]
 - VSCode version [e.g. 1.33.1]
 - Dependency Analytics Version [e.g. 0.0.22]

**CHE7/Theia(please complete the following information):**
 - OS: [e.g. macOS]
 - Browser [e.g. chrome]
 - CHE/Theia version 
 - Dependency Analytics Version [e.g. 0.0.22]

**Additional context**

**Comment by arajkumar** [comment] 2019-08-08 11:38
Couldn't reproduce it on my dev machine.

**Comment by invincibleJai** [comment] 2019-08-19 02:37
Closing as fixed. Feel free to reopen if not.

**Closed by invincibleJai** 2019-08-19 02:37 UTC
Labels: Analyzing
