### ISSUE TITLE
UI Freeze on repositories that have a very large number of pom.xml files

### ISSUE THREAD

**Issue by rootAvish** [fabric8-analytics/fabric8-analytics-vscode-extension#147] opened 2018-08-16 12:27 UTC
For the repository: https://github.com/apache/incubator-dubbo

There are a very large number of pom.xml files present, in these cases the UI freezes up and you are not able to switch tabs.

/cc @sara-02

**Comment by sara-02** [comment] 2018-08-16 15:58
How it looks, the actual recommendation tab is the little white space you see at the bottom of the screen, since the pom ist s huge, the stack report is pushed down, and there is no way to expand and roll it up.
![screenshot from 2018-08-16 12-49-19](https://user-images.githubusercontent.com/7047079/44220052-25253b80-a19b-11e8-96a5-c11e23f70df1.png)

**Comment by invincibleJai** [comment] 2018-08-19 17:52
i tried on mac couldn't reproduce i.e was able to scroll and UI was not frozen, could be an issue in fedora. 

Request other folks as well to give a try.

<img width="1680" alt="screen shot 2018-08-19 at 11 20 23 pm" src="https://user-images.githubusercontent.com/5129024/44311528-aaf8ef00-a406-11e8-9f0f-11445d1c8b86.png">
<img width="1680" alt="screen shot 2018-08-19 at 11 19 59 pm" src="https://user-images.githubusercontent.com/5129024/44311529-aaf8ef00-a406-11e8-9b0d-63133945aeda.png">

**Comment by ravsa** [comment] 2018-08-20 06:32
@invincibleJai  @sara-02  I tried with
```
vscode [ 1.25.1 ]
```
```
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 28 (Twenty Eight)
Release:	28
Codename:	TwentyEight
```
Not facing any UI freeze issue

**Comment by invincibleJai** [comment] 2018-08-24 08:50
To me it's more like an enhancement, as it's happening for few, may be we need to think about the way we are loading the stack-report-ui in web-view or in case of several manifest file should pull data using some sort of lazy loading. Even UXD is bad in such a scenario may need to revisit.

cc @samuzzal-choudhury

**Comment by sara-02** [comment] 2018-08-24 18:12
@invincibleJai yes, I will also keep a tab on of this and try with some other repos as well. If it does not happen we can close the issue.

**Comment by invincibleJai** [comment] 2019-03-14 15:30
Closing it, as didn't observed.

**Closed by invincibleJai** 2019-03-14 15:30 UTC
Labels: enhancement, ui
