### ISSUE TITLE
stack report generation starts from beginning when user navigates away and then revert back.

### ISSUE THREAD

**Issue by dev-gaur** [fabric8-analytics/fabric8-analytics-vscode-extension#69] opened 2018-01-18 09:26 UTC
While using VS code extension, stack report generation starts from beginning when I move away from the stack-report tab to some other tab and then revert back to the stack report tab. Lack of caching?

**Comment by invincibleJai** [comment] 2018-01-22 15:23
thanks @dev-gaur , possibly duplicate of https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/56

**Closed** 2018-01-23 02:39 UTC
Labels: duplicate, enhancement
