### ISSUE TITLE
Stack report for manifest file does not trigger any event due to CamelCasing

### ISSUE THREAD

**Issue by sara-02** [fabric8-analytics/fabric8-analytics-vscode-extension#152] opened 2018-08-23 08:29 UTC
An extension of the error: #151
While for whole workspace there is an error in the developer log, for the single manifest there is no developer log and no action is taken. When the camelcase is changed, it worked.
We should take some action, to generate the appropriate error, and bring it to the foreground. Because it looks as if the extension stopped working, even though that is not the case.

**Comment by samuzzal-choudhury** [comment] 2018-08-24 05:52
This is a duplicate of #150. Hence, closing.

**Closed by samuzzal-choudhury** 2018-08-24 05:52 UTC
Labels: bug

**Comment by samuzzal-choudhury** [comment] 2018-08-27 11:52
This issue was moved to openshiftio/openshift.io#4255
